import"./assets/styles-JE8YjOlG.js";import{a as c,i as a}from"./assets/vendor-ZnMw6IGI.js";const l="https://dummyjson.com",i=12,n={products:"/products",productById:"/products/",productsByCategory:"/products/category/",productsByQuery:"/products/search",categories:"/products/category-list"};c.defaults.baseURL=l;async function g(){const{data:t}=await c(n.categories);return t}async function u(t=1){const{data:e}=await c.get(n.products,{params:{limit:i,skip:(t-1)*i}});return e}async function p(t){const{data:e}=await c.get(`${n.productsByCategory}${t}`);return e}const o={categories:document.querySelector(".categories"),productsList:document.querySelector(".products"),notFound:document.querySelector(".not-found")};function y(t){const e=t.map(s=>`
      <li class="categories__item">
        <button class="categories__btn" type="button">${s}</button>
    </li>`).join("");o.categories.innerHTML=e}function d(t){const e=t.map(s=>`<li class="products__item" data-id="${s.id}">
    <img class="products__image" src="${s.thumbnail}" alt="${s.title}"/>
    <p class="products__title">${s.title}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand:</span>${s.brand}</p>
    <p class="products__category">Category: ${s.category}</p>
    <p class="products__price">Price: ${s.price}$</p>
 </li>`).join("");o.productsList.insertAdjacentHTML("beforeend",e)}function m(){o.productsList.innerHTML=""}function _(){const t=document.querySelector(".categories__btn");t&&t.classList.add("categories__btn--active")}function f(t){document.querySelectorAll(".categories__btn--active").forEach(s=>s.classList.remove("categories__btn--active")),t.classList.add("categories__btn--active")}async function b(){try{const t=await g();y(["all",...t]),_()}catch(t){console.log(t),a.error({message:"something went wrong"})}}async function L(){try{const{products:t}=await u();d(t)}catch(t){console.log(t),a.error({message:"something went wrong"})}}async function h(t){if(!t.target.classList.contains("categories__btn"))return;const e=t.target.textContent;f(t.target);try{let s=null;if(e==="all"){const{products:r}=await u();s=r}else{const{products:r}=await p(e);s=r}s.length===0?o.notFound.classList.add("not-found--visible"):o.notFound.classList.remove("not-found--visible"),m(),d(s)}catch(s){console.log(s),a.error({message:"something went wrong"})}}b();L();o.categories.addEventListener("click",h);
//# sourceMappingURL=index.js.map
